# Do not touch
version: 2.0.2

# The language locale which the plugin will translate its messages to
locale: en

# A list of commands which are allowed to use ingame
# Commands not included in this list won't be allowed to use while playing
# Adding an '*' (including quotes) will allow players to dispatch any command
game-allowed-commands:
- battlegrouds
- bg
- leave

# Arenas are protected from construct and destruction modifications
game-arena-protection: false

# Broadcast in-game chat message to the console
game-broadcast-chat: false

# The gamemode players get set to when joining and leaving a game
game-default-join-gamemode: SURVIVAL
game-default-leave-gamemode: SURVIVAL

# Displays a blood effect when certain entities get damaged
game-display-blood-effect:
  hellhound: true
  player: false
  zombie: true

# The general accuracy of firearms in the game
# Change to higher number for lower accuracy, change to lower number for higher accuracy
game-firearm-accuracy: 10.0

# Overall firearm damage modifier
# Change to lower number for higher damage, change to higher number for lower damage
game-firearm-damage-modifier: 1

# Game states where players are able to join games
game-joinable-states:
- Waiting

# The mob health bar configurations
game-mob-health-bar:
  # The end symbol of the mob health bar
  end-symbol: "&8]"
  # The health symbol of the current health of the mob on the health bar
  health-symbol: "|"
  # Amount of health symbols shown in the mob health bar
  length: 20
  # The first symbol of the mob health bar
  start-symbol: "&8["

# Some projectiles are able to pierce through certain block materials. Add their materials here
game-pierceable-materials:
- AIR
- BARRIER
- CARPET
- CROPS
- FENCE
- IRON_FENCE
- LADDER
- LEAVES
- LONG_GRASS
- REDSTONE_WIRE
- SIGN_POST
- STAINED_GLASS_PANE
- THIN_GLASS
- WALL_SIGN

# Scoreboard configurations
game-scoreboard:
  # Set to false to disable scoreboards
  enabled: true
  # The layout of the game scoreboards
  # Leave "" to remove this line
  lobby:
    layout:
      line0: "&6Countdown: &f%bg_countdown%s"
      line1: " "
      line2: "&6Players: &f%bg_players%"
      line3: "  "
      line4: "&6Gamemode: &f%bg_gamemode%"
      line5: "&6Arena: &f%bg_arena%"
      line6: "&8%bg_date%"
      title: "&6&lBattlegrounds"
    worlds: "*"

# The layout of the game joining signs
game-sign-layout:
  line-0: "%bg_state%"
  line-1: "&l%bg_gamemode%"
  line-2: "%bg_arena%"
  line-3: "&8&l%bg_players%/%bg_maxplayers%"

# Gamestate notations on game joining signs
game-sign-state:
  disabled: "&8&l[ DISABLED ]"
  ingame: "&4&l[ IN GAME ]"
  resetting: "&9&l[ RESETTING ]"
  starting: "&6&l[ STARTING ]"
  waiting: "&2&l[ WAITING ]"

# The minimum level players need to be to get access to custom loadout creation
loadout-creation-level: 4
